// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC8eMY9zBQf6L9Vg26_6cRcbiylJGwGWk',
    appId: '1:870642810925:web:e44e82537f1230e185b8a4',
    messagingSenderId: '870642810925',
    projectId: 'inspecciones-70d66',
    authDomain: 'inspecciones-70d66.firebaseapp.com',
    storageBucket: 'inspecciones-70d66.firebasestorage.app',
    measurementId: 'G-VVLQ2RWE9E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6vM1Z6cnN7SiWRpouEE2L6wIL5SZFt_Q',
    appId: '1:870642810925:android:68c68297be0fc7ae85b8a4',
    messagingSenderId: '870642810925',
    projectId: 'inspecciones-70d66',
    storageBucket: 'inspecciones-70d66.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwdagEmKCdHkaptZ2lXfrk7f1pFJd41q4',
    appId: '1:870642810925:ios:37093cde2c81528a85b8a4',
    messagingSenderId: '870642810925',
    projectId: 'inspecciones-70d66',
    storageBucket: 'inspecciones-70d66.firebasestorage.app',
    iosBundleId: 'com.example.inspecciones',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwdagEmKCdHkaptZ2lXfrk7f1pFJd41q4',
    appId: '1:870642810925:ios:37093cde2c81528a85b8a4',
    messagingSenderId: '870642810925',
    projectId: 'inspecciones-70d66',
    storageBucket: 'inspecciones-70d66.firebasestorage.app',
    iosBundleId: 'com.example.inspecciones',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAC8eMY9zBQf6L9Vg26_6cRcbiylJGwGWk',
    appId: '1:870642810925:web:cc64a058a6b9cd2b85b8a4',
    messagingSenderId: '870642810925',
    projectId: 'inspecciones-70d66',
    authDomain: 'inspecciones-70d66.firebaseapp.com',
    storageBucket: 'inspecciones-70d66.firebasestorage.app',
    measurementId: 'G-6QKBBJPMKJ',
  );
}
